name: Build and Release Flutter APK



on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3' # You can specify a Flutter version here

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

  create-release: # Job to create a new github release and upload the generated apk
    name: 🎉 Create Release
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - name: get repository name
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
      
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name:  app-release
      
      - name: Display Structure
        run: ls -R

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.run_number }}
          release_name:  ${{ env.REPOSITORY_NAME }} v${{ github.run_number }}

      - name: Upload Release APK
        id: upload_release_asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{github.token}}
        with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: app-release.apk
         asset_name:  ${{ env.REPOSITORY_NAME }}.apk
         asset_content_type: application/zip
